### ISSUE TITLE
-h gives conflicting information regarding default data cache kind

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos-simulator#17]
When running `pasim -h` the following is printed regarding the data cache kind:

```
-D [ --dckind ] arg (=dm)             kind of direct mapped/fully-/set-associ
                                        ative data cache, defaults to lru2
                                        (ideal, no, dm, lru[N], fifo[N])
```

The `(=dm)` should signify that a direct mapping is used when the flag is not set, however the description then says `defaults to lru2`.

Running some tests, it seems to me that direct mapping is indeed the default when the flag is not set.
We should decide which kind should be default and correct the message to fit.

**Comment by Emoun** [comment]
@schoeberl do you have input on this? What does the default configuration of patmos use?

**Comment by schoeberl** [comment]
The default configuration on Patmos (hardware) is a direct-mapped data cache with write-through.
