### ISSUE TITLE
pasim requires boost-program-options to run

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos-simulator#6]
The release binary for `pasim` that we provide prebuilt requires boost-program-options v1.65.1 to be installed on the machine that runs pasim. 

This issue is to discuss whether we want to keep this, or change `pasim` to statically link boost and therefore not require users to have boost installed.

If we keep the status quo, we will have to instruct users to install boost as part of installing `pasim`, which is more work on their part. However, in the future, we might provide an ubuntu package for `pasim`, in which case we can make boost a dependency and the user wont have to do it on their own.

Thoughts?

**Comment by schoeberl** [comment]
Personally I find getting a boost dependency just for a little bit of option processing a very heavy dependency for little function. Option processing could be done in plain C in a few lines of code.

Cheers,
Martin

**Comment by Emoun** [comment]
I quickly counted `src/pasim.cc` and found 65 different options in the current code.

I think it would be too big of a job to convert the current implementation into a hand-rolled one. Not only are there many options, some of them also have specific defaults that need to maintained.
The current code uses ~200 lines to parse the options, when using boost-program-options, this would be much more if we had to implement it all by hand. I don't think it's a trivial job.

We should also note that this doesn't use all of boost, just the boost-program-options component.
I don't think it's worth it time-wise to begin making changes to this code that works.
However, statically linking boost-program-options should just be a change to the cmake config.

**Comment by Emoun** [comment]
@schoeberl do you have any more thoughts on this? Otherwise I'm leaning towards statically linking and will look into making the change when I have some time.

**Comment by Emoun** [comment]
As can be seen [in this comment](https://github.com/t-crest/patmos-simulator/issues/2#issuecomment-646000197), it is not possible to statically link Boost's `program_options` for OSX.
