### ISSUE TITLE
Test 14

### ISSUE THREAD

**Issue by simonamtoft** [t-crest/patmos-simulator#7]
A load instruction is allowed on bundle slot 2 (pipeline 2).

**Comment by Emoun** [comment]
@Simonipsum can I get you to provide an example program that exhibits this behavior and what you would have expected `pasim` to do instead?

**Comment by Emoun** [comment]
Also, what is "Test 14" a reference to ?

**Comment by Emoun** [comment]
@schoeberl Do you know anything about this? otherwise I will close the issue since @Simonipsum is not answering.

**Comment by Emoun** [comment]
Closing the issue because of a lack of response from @Simonipsum.
