### ISSUE TITLE
Test 46

### ISSUE THREAD

**Issue by simonamtoft** [t-crest/patmos-simulator#8]
Paasm wont compile with "ret" instruction using r30 and r31 on line 49.

**Comment by Emoun** [comment]
@Simonipsum can I get you to provide an example program that exhibits this behavior, what error message you are getting, and what "line 49" and "Test 46" are references to?

**Comment by Emoun** [comment]
@schoeberl Do you know anything about this? Otherwise I will close the issue since @Simonipsum is not answering.

**Comment by Emoun** [comment]
Closing the issue because of a lack of response from @Simonipsum.
